
# Nom pour GitHub Actions
name: Java CI with Gradle
# Evènements déclancheur Toutes branches
# on: [push]
# Evènements déclancheur branches main et develop uniquement
on:
  push:
    branches: [main, develop]

# Liste des jobs
jobs:
  # Nom du job
  build:
    # Image docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.0
      with:
        gradle-version: 7.6
        arguments: build
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs
